apiVersion: v1
kind: Service
metadata:
  name: owasp-juice-shop-service
spec:
  type: LoadBalancer
  ports:
#    - name: webapp
    - port: 3000
      targetPort: 3000
  selector:
    app: owasp-juice-shop
